import { Product } from "./types";

export const products: Product[] = [
  // ── WOMEN'S BAGS ─────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Spherical Fashion Clutch Bag",
    category: "Women's Bags",
    price: 19.10,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80",
    description: "Round purse with detachable strap and zipper closure. A bold statement piece for evenings and special events.",
    badge: "New",
    rating: 4.7,
    reviews: 312,
    quantity: 1000,
  },
  {
    id: 2,
    name: "Glossy Patent Leather Top Handle Bag",
    category: "Women's Bags",
    price: 22.50,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    description: "Crossbody top-handle purse with strap. Elegant faux patent leather finish for the modern woman.",
    badge: "Popular",
    rating: 4.8,
    reviews: 489,
    quantity: 1800,
  },
  {
    id: 3,
    name: "Faux Snakeskin Chain Pouch Bag",
    category: "Women's Bags",
    price: 15.01,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80",
    description: "Textured crossbody purse with linked chain strap. Compact fashion handbag with exotic snakeskin look.",
    rating: 4.5,
    reviews: 203,
    quantity: 1499,
  },
  {
    id: 4,
    name: "Pleated Faux Leather Shoulder Bag",
    category: "Women's Bags",
    price: 13.15,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80",
    description: "Soft textured crossbody purse with adjustable strap. Casual everyday handbag with pleated design.",
    badge: "Sale",
    rating: 4.4,
    reviews: 178,
    quantity: 1600,
  },
  {
    id: 5,
    name: "Faux Leather Clutch with Shoulder Chain",
    category: "Women's Bags",
    price: 13.15,
    image: "https://images.unsplash.com/photo-1614179924047-e1ab49a0a0cf?w=600&q=80",
    description: "Trendy fashion purse with chain shoulder strap. Versatile handbag that goes from day to night effortlessly.",
    rating: 4.6,
    reviews: 267,
    quantity: 1200,
  },
  {
    id: 6,
    name: "Faux Leather Top Handle Crossbody Bag",
    category: "Women's Bags",
    price: 14.00,
    originalPrice: 22.00,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80",
    description: "Flap shoulder purse with adjustable strap. Classic structured silhouette at an unbeatable price.",
    badge: "Sale",
    rating: 4.5,
    reviews: 143,
    quantity: 699,
  },
  {
    id: 7,
    name: "Faux Leather Chain Clutch Bag",
    category: "Women's Bags",
    price: 17.40,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    description: "Shoulder purse with chain and leather strap. A sophisticated fashion purse for women who love style.",
    rating: 4.7,
    reviews: 321,
    quantity: 1600,
  },
  {
    id: 8,
    name: "Graffiti Print Faux Leather Crossbody Bag",
    category: "Women's Bags",
    price: 33.96,
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80",
    description: "Adjustable strap top handle purse with bold graffiti print. Compact everyday handbag that makes a statement.",
    badge: "Hot",
    rating: 4.9,
    reviews: 512,
    quantity: 2500,
  },
  {
    id: 9,
    name: "Quilted Faux Leather Top Handle Bag",
    category: "Women's Bags",
    price: 19.95,
    image: "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?w=600&q=80",
    description: "Structured crossbody shoulder purse with quilted detailing and adjustable strap. Elegant and timeless.",
    badge: "New",
    rating: 4.6,
    reviews: 198,
    quantity: 599,
  },
  {
    id: 10,
    name: "Embossed Faux Leather Flap Bag",
    category: "Women's Bags",
    price: 48.00,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    description: "Chain strap crossbody shoulder purse with embossed detailing. Structured compact handbag for daily use.",
    badge: "Popular",
    rating: 4.8,
    reviews: 276,
    quantity: 899,
  },
  {
    id: 11,
    name: "Studded Monotone Clutch Bag",
    category: "Women's Bags",
    price: 17.40,
    image: "https://images.unsplash.com/photo-1575032617751-6ddec2089882?w=600&q=80",
    description: "Faux leather envelope evening crossbody purse with adjustable strap. Perfect for parties and events.",
    rating: 4.5,
    reviews: 134,
    quantity: 999,
  },
  {
    id: 12,
    name: "Embossed PU Leather Flap Bag",
    category: "Women's Bags",
    price: 13.15,
    image: "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80",
    description: "Textured shoulder purse with adjustable crossbody strap and flap closure. Chic and affordable everyday bag.",
    badge: "Sale",
    rating: 4.4,
    reviews: 189,
    quantity: 1999,
  },
  {
    id: 13,
    name: "Woven Faux Leather Bucket Bag",
    category: "Women's Bags",
    price: 32.76,
    image: "https://images.unsplash.com/photo-1473188588951-666fce8e7c68?w=600&q=80",
    description: "Open weave drawstring purse with top handle and crossbody strap. A boho-chic must-have for summer.",
    rating: 4.7,
    reviews: 234,
    quantity: 1300,
  },
  {
    id: 14,
    name: "Shiny Croc Embossed Bag",
    category: "Women's Bags",
    price: 19.95,
    image: "https://images.unsplash.com/photo-1516488756856-ee3a2b93cd9c?w=600&q=80",
    description: "Glossy PU leather crossbody purse with top handle and chain strap. Small fashion handbag with luxe croc texture.",
    badge: "New",
    rating: 4.6,
    reviews: 167,
    quantity: 1900,
  },
  {
    id: 15,
    name: "Rhinestone Crossbody Bag with Coin Purse",
    category: "Women's Bags",
    price: 49.00,
    image: "https://images.unsplash.com/photo-1523178514284-f30dcb3fae82?w=600&q=80",
    description: "Sparkly chain strap shoulder handbag with matching round mini coin purse. Compact evening party bag.",
    badge: "Hot",
    rating: 4.9,
    reviews: 623,
    quantity: 1800,
  },
  {
    id: 16,
    name: "Sequin Handle Crossbody Bag",
    category: "Women's Bags",
    price: 20.63,
    image: "https://images.unsplash.com/photo-1567401893450-a2d97b1ffd6e?w=600&q=80",
    description: "Sparkly evening shoulder purse with adjustable strap. Party handbag that catches every light.",
    badge: "Sale",
    rating: 4.7,
    reviews: 298,
    quantity: 1799,
  },
  {
    id: 17,
    name: "Women's Casual Shoulder Bag",
    category: "Women's Bags",
    price: 53.13,
    image: "https://images.unsplash.com/photo-1576016770956-bfcf8e81c01f?w=600&q=80",
    description: "Spacious casual handbag with a relaxed yet stylish design. Perfect for everyday errands and outings.",
    rating: 4.5,
    reviews: 156,
    quantity: 1499,
  },
  {
    id: 18,
    name: "Striped Straw Phone Crossbody Bag",
    category: "Women's Bags",
    price: 10.51,
    image: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=600&q=80",
    description: "Woven mini cellphone purse with adjustable strap. Lightweight summer shoulder bag for your essentials.",
    badge: "Sale",
    rating: 4.3,
    reviews: 87,
    quantity: 299,
  },
  {
    id: 19,
    name: "Tweed Plaid Tote Bag",
    category: "Women's Bags",
    price: 69.35,
    image: "https://images.unsplash.com/photo-1591373032221-1c8a0a51e668?w=600&q=80",
    description: "Textured fabric shoulder handbag with top handles. Lightweight everyday carryall with sophisticated tweed style.",
    badge: "Popular",
    rating: 4.8,
    reviews: 345,
    quantity: 1899,
  },
  {
    id: 20,
    name: "Round Wristlet Bag with Strap",
    category: "Women's Bags",
    price: 25.05,
    image: "https://images.unsplash.com/photo-1540979388789-4ad2d0b5d925?w=600&q=80",
    description: "PU leather clutch purse with adjustable strap. Compact lightweight handheld fashion bag in a unique round shape.",
    rating: 4.6,
    reviews: 112,
    quantity: 888,
  },
  {
    id: 21,
    name: "Quilted PU Leather Bucket Bag",
    category: "Women's Bags",
    price: 36.45,
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c827ad?w=600&q=80",
    description: "Drawstring shoulder handbag with adjustable strap. Lightweight everyday crossbody purse with chic quilted design.",
    badge: "New",
    rating: 4.7,
    reviews: 221,
    quantity: 1100,
  },
  {
    id: 22,
    name: "Round Bamboo Crossbody Bag",
    category: "Women's Bags",
    price: 54.69,
    image: "https://images.unsplash.com/photo-1594938298603-e8ce8c19e456?w=600&q=80",
    description: "Woven summer shoulder purse with strap. Lightweight beach handbag with natural bamboo-inspired handle.",
    badge: "Popular",
    rating: 4.8,
    reviews: 289,
    quantity: 1599,
  },
  {
    id: 23,
    name: "PU Leather Classic Crossbody Bag",
    category: "Women's Bags",
    price: 13.15,
    image: "https://images.unsplash.com/photo-1606521975680-4f34e73c0a8b?w=600&q=80",
    description: "Classic pattern shoulder purse with adjustable strap and top handle. A reliable everyday handbag.",
    badge: "Sale",
    rating: 4.4,
    reviews: 198,
    quantity: 1300,
  },
  {
    id: 24,
    name: "Graffiti Print Boston Bag",
    category: "Women's Bags",
    price: 20.35,
    image: "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&q=80",
    description: "Travel shoulder handbag with top handles and strap. Bold graffiti print fashion bag for the trendsetter.",
    rating: 4.6,
    reviews: 76,
    quantity: 598,
  },
  {
    id: 25,
    name: "Metallic Faux Straw Tote with Pouch",
    category: "Women's Bags",
    price: 19.10,
    image: "https://images.unsplash.com/photo-1579558895462-e7e53b855fe0?w=600&q=80",
    description: "Handbag set with matching pouch. Summer beach travel carryall with shimmery metallic straw texture.",
    rating: 4.5,
    reviews: 143,
    quantity: 699,
  },
  {
    id: 26,
    name: "Graphic Letter Print Clutch Bag",
    category: "Women's Bags",
    price: 49.00,
    image: "https://images.unsplash.com/photo-1565116175827-965bece9e2a1?w=600&q=80",
    description: "PU leather envelope handbag with wristlet strap. Chic graphic letter print clutch for women.",
    badge: "New",
    rating: 4.7,
    reviews: 167,
    quantity: 899,
  },
  {
    id: 27,
    name: "Multi Snake Print Quilted Mini Bag",
    category: "Women's Bags",
    price: 19.75,
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?w=600&q=80",
    description: "Compact PU leather crossbody purse with chain strap and snake print quilted pattern. Fashion shoulder bag.",
    rating: 4.6,
    reviews: 234,
    quantity: 1398,
  },
  {
    id: 28,
    name: "Graffiti Gradient Clutch Bag",
    category: "Women's Bags",
    price: 25.02,
    image: "https://images.unsplash.com/photo-1613682028565-ff7820bade63?w=600&q=80",
    description: "Envelope handbag with wrist strap and chain. Multicolor graffiti gradient compact PU leather purse.",
    badge: "Hot",
    rating: 4.8,
    reviews: 312,
    quantity: 1198,
  },

  // ── ACCESSORIES ──────────────────────────────────────────────────────────────
  {
    id: 29,
    name: "Multi Pearl Beaded Bracelet Set",
    category: "Accessories",
    price: 31.66,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    description: "Classic faux pearl fashion bracelets for women. Wrist jewelry set that elevates any look.",
    badge: "Popular",
    rating: 4.8,
    reviews: 445,
    quantity: 1999,
  },
  {
    id: 30,
    name: "Faux Straw Wide Brim Sun Hat",
    category: "Accessories",
    price: 49.10,
    image: "https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?w=600&q=80",
    description: "Breathable wide brim summer beach hat for women. Foldable outdoor travel cap with UV protection.",
    badge: "New",
    rating: 4.7,
    reviews: 198,
    quantity: 1199,
  },
  {
    id: 31,
    name: "Faux Straw Sun Hat — Classic",
    category: "Accessories",
    price: 20.80,
    image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80",
    description: "Lightweight breathable summer beach hat. Foldable outdoor travel cap — an essential summer accessory.",
    badge: "Sale",
    rating: 4.5,
    reviews: 134,
    quantity: 399,
  },
  {
    id: 32,
    name: "Animal Print Zip Around Wallet",
    category: "Accessories",
    price: 14.00,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
    description: "PU leather card holder clutch with coin pocket and organizer. Stylish zip-around wallet with animal print.",
    rating: 4.4,
    reviews: 267,
    quantity: 1399,
  },
  {
    id: 33,
    name: "Water Bottle Holder Crossbody Bag",
    category: "Accessories",
    price: 55.00,
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80",
    description: "Insulated drink carrier pouch with chain strap. Hands-free shoulder sling bag for travel, gym, and outdoors.",
    badge: "Hot",
    rating: 4.9,
    reviews: 523,
    quantity: 1999,
  },

  // ── BEAUTY & FRAGRANCE ───────────────────────────────────────────────────────
  {
    id: 34,
    name: "Fragrance Mist Spray for Women",
    category: "Beauty & Fragrance",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4ee6c05?w=600&q=80",
    description: "Refreshing scent portable travel size perfume mist. Includes 2 random bottles of body spray for women.",
    badge: "Popular",
    rating: 4.7,
    reviews: 389,
    quantity: 1400,
  },
  {
    id: 35,
    name: "Perfume and Lotion Gift Set for Women",
    category: "Beauty & Fragrance",
    price: 49.00,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    description: "Luxurious perfume and lotion gift set. A beautifully packaged present for any special occasion.",
    badge: "New",
    rating: 4.8,
    reviews: 234,
    quantity: 1300,
  },

  // ── HOME & LIVING ─────────────────────────────────────────────────────────────
  {
    id: 36,
    name: "Red, White & Blue Lounge Throw",
    category: "Home & Living",
    price: 25.73,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    description: "60\" x 70\" soft lounge throw blanket in patriotic colors. Perfect for couch lounging and movie nights.",
    rating: 4.6,
    reviews: 312,
    quantity: 2599,
  },
  {
    id: 37,
    name: "Oversized Beach Towel 40\" x 72\"",
    category: "Home & Living",
    price: 25.05,
    image: "https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=600&q=80",
    description: "Member's Mark oversized beach towel — large enough for two. Perfect for swimming pools, beach, and travel.",
    badge: "Popular",
    rating: 4.7,
    reviews: 456,
    quantity: 1999,
  },
  {
    id: 38,
    name: "Bed Pillows — Assorted Sizes",
    category: "Home & Living",
    price: 59.49,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=80",
    description: "Premium bed pillows in queen and king sizes. Supportive fill for a restful night's sleep every night.",
    rating: 4.5,
    reviews: 289,
    quantity: 1199,
  },
  {
    id: 39,
    name: "Beach Towel — Large",
    category: "Home & Living",
    price: 23.79,
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80",
    description: "Large towel for swimming pool, beach, and travel use. Quick-dry, absorbent, and lightweight.",
    badge: "Sale",
    rating: 4.4,
    reviews: 167,
    quantity: 1300,
  },
  {
    id: 40,
    name: "Wire Storage Baskets, Set of 2",
    category: "Home & Living",
    price: 38.69,
    image: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80",
    description: "Member's Mark wire baskets for storage and organization. Stylish and functional for any room.",
    rating: 4.6,
    reviews: 234,
    quantity: 1800,
  },
  {
    id: 41,
    name: "Ultra Premium 2-Ply Toilet Paper 45 Rolls",
    category: "Home & Living",
    price: 149.00,
    image: "https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=600&q=80",
    description: "Member's Mark 235 sheets/roll, 45 rolls. Soft, strong, and septic-safe premium toilet tissue.",
    badge: "Popular",
    rating: 4.8,
    reviews: 678,
    quantity: 2200,
  },
  {
    id: 42,
    name: "Soft & Strong Facial Tissues 12 Boxes",
    category: "Home & Living",
    price: 70.00,
    image: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=600&q=80",
    description: "Member's Mark 2-ply premium facial tissues, 12 flat boxes, 160 tissues/box. Gentle on skin.",
    rating: 4.7,
    reviews: 345,
    quantity: 1200,
  },
  {
    id: 43,
    name: "Select & Tear 2-Ply Paper Towels 15 Rolls",
    category: "Home & Living",
    price: 99.00,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
    description: "Member's Mark 150 sheets/roll, 15 rolls. Select-a-size paper towels for everyday household tasks.",
    badge: "Popular",
    rating: 4.8,
    reviews: 512,
    quantity: 1100,
  },
  {
    id: 44,
    name: "55 Gallon Drum Liner Trash Bags 80 Count",
    category: "Home & Living",
    price: 34.16,
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
    description: "Heavy-duty extra-large trash bags for drum liners and large garbage cans. 80 bags per box.",
    rating: 4.5,
    reviews: 198,
    quantity: 1300,
  },

  // ── KITCHEN & DINING ─────────────────────────────────────────────────────────
  {
    id: 45,
    name: "Printed Paper Cups — Mega Party Pack",
    category: "Kitchen & Dining",
    price: 85.00,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    description: "Disposable cups mega pack for parties and celebrations. Fun printed designs for birthdays and holidays.",
    badge: "Popular",
    rating: 4.6,
    reviews: 289,
    quantity: 6699,
  },
  {
    id: 46,
    name: "Printed Paper Cups — Large Bundle",
    category: "Kitchen & Dining",
    price: 22.26,
    image: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80",
    description: "Disposable drinking cups for parties. Large bundle pack for birthdays, Christmas, and Easter celebrations.",
    badge: "Sale",
    rating: 4.5,
    reviews: 178,
    quantity: 5500,
  },
  {
    id: 47,
    name: "White Napkins 4 Extra-Large Packs",
    category: "Kitchen & Dining",
    price: 55.00,
    image: "https://images.unsplash.com/photo-1530018352490-c6eef07fd7b6?w=600&q=80",
    description: "Member's Mark everyday 1-ply white napkins. 4 extra-large packs, 300 napkins/pack.",
    rating: 4.7,
    reviews: 234,
    quantity: 999,
  },
  {
    id: 48,
    name: "Food Storage Container Set",
    category: "Kitchen & Dining",
    price: 26.70,
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
    description: "Versatile food storage containers for kitchen and grocery. Keep food fresh with airtight seals.",
    badge: "New",
    rating: 4.6,
    reviews: 312,
    quantity: 1100,
  },
  {
    id: 49,
    name: "Patriotic Oval Paper Plates 10 Count",
    category: "Kitchen & Dining",
    price: 14.00,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    description: "Member's Mark 10\" x 12\" patriotic paper plates. Perfect for Independence Day and patriotic celebrations.",
    rating: 4.4,
    reviews: 145,
    quantity: 3300,
  },
  {
    id: 50,
    name: "Spring Oval Paper Plates 50 Count",
    category: "Kitchen & Dining",
    price: 16.79,
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=600&q=80",
    description: "Member's Mark spring-themed 10\" x 12\" oval plates, 50 ct. Bring seasonal cheer to your table.",
    rating: 4.5,
    reviews: 189,
    quantity: 3300,
  },
  {
    id: 51,
    name: "Fancy Florals Spring Paper Plates 17 Count",
    category: "Kitchen & Dining",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=600&q=80",
    description: "Member's Mark fancy floral 10\" spring paper plates, 17 ct. Beautiful table presentation.",
    rating: 4.6,
    reviews: 234,
    quantity: 2900,
  },
  {
    id: 52,
    name: "Nonstick Frying Pan 12.5 Inch with Glass Lid",
    category: "Kitchen & Dining",
    price: 16.90,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    description: "Nonstick fry pan cookware with tempered glass lid. 12.5-inch diameter — perfect for everyday cooking.",
    badge: "New",
    rating: 4.7,
    reviews: 345,
    quantity: 897,
  },
  {
    id: 53,
    name: "Food Warming Mat 5-Piece Set",
    category: "Kitchen & Dining",
    price: 19.75,
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&q=80",
    description: "Large food warming mat with towel and spatulas. Foldable tray for parties and daily kitchen use.",
    rating: 4.5,
    reviews: 167,
    quantity: 999,
  },

  // ── OUTDOORS & SPORTS ─────────────────────────────────────────────────────────
  {
    id: 54,
    name: "Outdoor Picnic Blanket / Beach Mat",
    category: "Outdoors & Sports",
    price: 42.42,
    image: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600&q=80",
    description: "Member's Mark foldable outdoor blanket for camping, travel, grass, and garden. Waterproof backing.",
    badge: "Popular",
    rating: 4.8,
    reviews: 423,
    quantity: 599,
  },
  {
    id: 55,
    name: "Golf Balls Bundle Pack of 24",
    category: "Outdoors & Sports",
    price: 46.06,
    image: "https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=600&q=80",
    description: "Member's Mark golf balls, 24-pack. Consistent flight and feel for golfers of all skill levels.",
    rating: 4.7,
    reviews: 289,
    quantity: 1599,
  },
  {
    id: 56,
    name: "8' Beach Umbrella",
    category: "Outdoors & Sports",
    price: 42.89,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    description: "Member's Mark 8-foot beach umbrella for beach, garden, and pool shade. Easy setup and sturdy design.",
    badge: "New",
    rating: 4.6,
    reviews: 198,
    quantity: 699,
  },
  {
    id: 57,
    name: "5-Position Beach Chair with Wooden Armrest",
    category: "Outdoors & Sports",
    price: 62.37,
    image: "https://images.unsplash.com/photo-1540979388789-4ad2d0b5d925?w=600&q=80",
    description: "Member's Mark folding chair for beach and camping. 5 reclining positions and solid wooden armrests.",
    badge: "Hot",
    rating: 4.9,
    reviews: 534,
    quantity: 599,
  },
  {
    id: 58,
    name: "Everyday White Napkins — 4 Packs",
    category: "Kitchen & Dining",
    price: 55.00,
    image: "https://images.unsplash.com/photo-1484659619207-9165d119dafe?w=600&q=80",
    description: "Member's Mark extra-large packs of 300 white napkins each. Ideal for restaurants, catering, and large events.",
    rating: 4.6,
    reviews: 178,
    quantity: 999,
  },
];

export const categories = [
  "All",
  "Women's Bags",
  "Accessories",
  "Beauty & Fragrance",
  "Home & Living",
  "Kitchen & Dining",
  "Outdoors & Sports",
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "Hot" || p.badge === "Popular").slice(0, 8);
}
